### ISSUE TITLE
iOS8?

### ISSUE THREAD

**Issue by davehodg** [dirkz/iNetHack#1]
Have you tried it in iOS8? 
The latest version keeps freezing.

**Comment by dirkz** [comment]
There is some discussion on https://groups.google.com/forum/?hl=en_US#!forum/inethack-beta-testers about how to revive iNetHack and make it work on iOS 8.

**Comment by davehodg** [comment]
Cool. I've applied to join.

**Comment by dirkz** [comment]
Should be fixed now by Jeff :)
